package com.project.bsky.bean;

import lombok.Data;
import lombok.ToString;

@Data
@ToString
public class HospitalCivilInfrastructure {

	private Integer hospitalId;
	private String saveOrUpdate;
	private Integer createdByOrUpdatedBy;
	private Character standardisedArchDesign;
	private Character fireFightingSystem;
	private Character bioMedicalWasteManagement;
	private Character dutyStaffRoom;
	private Character cattleTrapAtEntranceAndExit;
	private Integer areaBed;
	private Character backUpElectricitySupply;
	private Integer noOfFloors;
	private Character liftProvision;
	private Character rampProvision;
	private Integer totalBedStrength;
	private Integer noOfInPatientBeds;
	private Character fullyEquipiedOperationTheatre;
	private Integer totalNoOfBedsFullyEquipedOperationTheatre;
	private Character opd;
	private Integer totallNoOfBedopd;
	private Character hdu;
	private Integer totallNoOfBedHDU;
	private Character generalWard;
	private Integer totallNoOfBedgeneralWard;
	private Character icu;
	private Integer totalNoOfBedICU;
	private Character icuwv;
	private Integer totalNoOfBedICUwv;
	private Character icuwov;
	private Integer totalNoOfBedICUwov;	
	private Character casualty;
	private Integer totalNoOfBedCasualty;
	private Character labourRoom;
	private Integer totalNoOfRoomLabourRoom;
	private Character bloodBank;
	private Character cssd;
	private Character dietAndKitchenFacility;
	private Character linenAndLaundry;
	private Character stores;
	private Character medicalRecordsDepartment;
	private Character ambulanceService;
	private Character patientAttendantFacility;
	private Character diagnosticCentreRadiologyBasic;
	private Character diagnosticCentreRadiologyAdvanced;
	private Character diagnosticCentreClinicalLabAndDiagnostics;
	private Integer wallsShouldBeCovered;
	private Integer availabilityOfSeparateOTs;
	private Character availabilityOfPreOperative;
	private Character availabilityOfPostOperative;
	private Character separateChangingRooms;
	private Character dedicatedScrubArea;
	private Character waitingRoomForPatientsAndRelatives;
	private Character registrationCounter;
	private Character doctorConsultantRooms;
	private Character dressingRoom;
	private Character injectionRoom;
	private Character pharmacyWindow;
	private Character plasterRoom;
	private Character separateStandForStaffPublicVehicles;
	private Character sanitaryFitments;
	private Character hduMultiSignMonitoringSystem;
	private Character hduOxygenSupply;
	private Character hduPipedSuctionAndMedicalGases;
	private Character hduInfusionOfIonotropicSupport;
	private Character hduEquipmentForMaintenanceOfBodyTemperature;
	private Character hduWeighingScale;
	private Character hduManpowerForMonitoring;
	private Character hduEmergencyCashCart;
	private Character hduUninterruptedElectricSupply;
	private Character hduHeating;
	private Character hduAirConditioning;
	private Integer hduTotalNoOfBed;
	private Character icuMultiSignMonitoringSystem;
	private Character icuOxygenSupply;
	private Character icuPipedSuctionAndMedicalGases;
	private Character icuInfusionOfIonotropicSupport;
	private Character icuEquipmentForMaintenanceOfBodyTemperature;
	private Character icuWeighingScale;
	private Character icuManpowerForMonitoring;
	private Character icuEmergencyCashCart;
	private Character icuUninterruptedElectricSupply;
	private Character icuHeating;
	private Character icuAirConditioning;
	private Integer icuTotalNoOfBed;
}
